const productsData = {
    newProducts: [{

            id: 1,
            name: "Dép Crocband Clog",
            image: "../image/ip1.png",
            price: 4990000,
            promotion: "new",
        },
        {
            id: 2,
            name: "Dép Baya Clog",
            image: "../image/ip2.png",
            price: 12190000,
            promotion: "new",
        },
        {
            id: 3,
            name: "Dép Classic Lined Clog",
            image: "../image/ip15.jpg",
            price: 16400000,
            decrease: 14368000,
            discount: "-33%",
        },
        {
            id: 4,
            name: "iCrocs Mega Crush Clog",
            image: "../image/g13.webp",
            price: 12400000,
            promotion: "new",
        },

        {
            id: 5,
            name: "Giày Nike Air Force 1",
            image: "../image/ip14.jpg",
            price: 3070000,
            promotion: "new",
        },
        {
            id: 6,
            name: "Dép Đế Xuồng Nữ Crocs Brooklyn Luxe Cross Strap",
            image: "../image/ip4.jpg",
            price: 2190900,
            decrease: 17290000,
            discount: "-21%",
        },
        {
            id: 7,
            name: "Nike Air Force 1 '07 Low",
            image: "../image/ip5.png",
            price: 2550000,
            decrease: 1850000,
            discount: "-20%",
        },
        {
            id: 8,
            name: "Giày Crocs Retro Clog",
            image: "../image/ip6.jpg",
            price: 2600000,
            decrease: 2000000,
            discount: "-10%",
        },
        {
            id: 9,
            name: "Nike Downshifter 13",
            image: "../image/ip9.jpg",
            price: 2255500,
            promotion: "new",
        },
        {
            id: 10,
            name: "Nike SB Chron 2",
            image: "../image/ip13.jpg",
            price: 3076000,
        },
        {
            id: 11,
            name: "Mega Crush Clog ",
            image: "../image/ip21.jpg",
            price: 499900,
            promotion: "new",
        },
        {
            id: 12,
            name: "Nike Interact Run SE",
            image: "../image/ip25.jpg",
            price: 4240000,
        },
        {
            id: 13,
            name: "Nike Downshifter 13",
            image: "../image/ip13.jpg",
            price: 2330000,
        },
        {
            id: 14,
            name: "iNike Air Jordan 1 Retro High OG",
            image: "../image/ip14.jpg",
            price: 3070000,
            promotion: "new",
        },
        {
            id: 15,
            name: "Nike Air Max 2024 ",
            image: "../image/ip15.jpg",
            price: 1640000,
            decrease: 836000,
            discount: "-33%",
        },
        {
            id: 16,
            name: "Nike Cortez Leather",
            image: "../image/ip25.jpg",
            price: 4500000,
            promotion: "new",
        },
        {
            id: 17,
            name: "Nike Cortez Leather",
            image: "../image/ip17.jpg",
            price: 2213000,
            promotion: "new",
        },
        {
            id: 18,
            name: "Nike SB Chron 2 ",
            image: "../image/ip18.jpg",
            price: 6550000,
            promotion: "new",
        },
        {
            id: 19,
            name: "Crocs Brooklyn Upper Low Wedge",
            image: "../image/ip19.jpg",
            price: 7200000,
            promotion: "new",
        },
        {
            id: 20,
            name: "Giày Đế Xuồng Nữ Crocs Brooklyn Luxe Cross Strap",
            image: "../image/ip20.jpg",
            price: 11650000,
            decrease: 10485000,
            discount: "-10%",
        },
        {
            id: 21,
            name: "Giày Nike ZoomX Invincible Run Flyknit 3",
            image: "../image/ip21.jpg",
            price: 1090000,
        },
        {
            id: 22,
            name: "Giày Nike Air Jordan 1 Retro High UNC",
            image: "../image/ip22.jpg",
            price: 6200000,
        },
        {
            id: 23,
            name: "Giày Nike Cortez Leather",
            image: "../image/ip23.jpg",
            price: 5870000,
        },
        {
            id: 24,
            name: "Giày Nike Air Jordan 1 Retro High OG Chicago",
            image: "../image/ip24.jpg",
            price: 1350000,
            decrease: 1033000,
            discount: "-10%",
        },
    ],
    Giaynam: [{

            id: 1,
            name: "Giày Clog Unisex Crocs Classic - Graphite",
            image: "../image/g1.webp",
            price: 4990000,
            promotion: "new",
        },
        {
            id: 2,
            name: "Giày Clog Unisex Crocs Classic - Camo",
            image: "../image/g2.webp",
            price: 3319000,
            promotion: "new",
        },
        {
            id: 3,
            name: "Giày Clog Unisex Crocs Classic - Neon Green",
            image: "../image/g3.webp",
            price: 1640000,
            decrease: 1436800,
            discount: "-9%",
        },
        {
            id: 4,
            name: "Giày Clog Unisex Crocs Classic - Light Blue",
            image: "../image/g4.webp",
            price: 1240000,
            promotion: "new",
        },

        {
            id: 5,
            name: "Giày Clog Unisex Crocs Classic - Lilac",
            image: "../image/g5.webp",
            price: 3070000,
            promotion: "new",
        },
        {
            id: 6,
            name: "Giày Clog Unisex Crocs Classic - Buttercup ",
            image: "../image/g6.webp",
            price: 2199000,
            decrease: 1729000,
            discount: "-21%",
        },
        {
            id: 7,
            name: "Giày Clog Unisex Crocs Classic - Pink Lemonade",
            image: "../image/g7.webp",
            price: 2550000,
            decrease: 1850000,
            discount: "-20%",
        },
        {
            id: 8,
            name: "Giày Clog Unisex Crocs Classic - Khaki",
            image: "../image/g8.webp",
            price: 2600000,
            decrease: 2000000,
            discount: "-10%",
        },

        {
            id: 9,
            name: "Giày Clog Unisex Crocs Classic - Bright Coral",
            image: "../image/g9.webp",
            price: 22555000,
            promotion: "new",
        },
        {
            id: 10,
            name: "Giày Clog Unisex Crocs Classic - Slate Grey",
            image: "../image/g10.webp",
            price: 3076000,
        },
        {
            id: 11,
            name: "Giày Clog Unisex Crocs Classic - Mint",
            image: "../image/g11.webp",
            price: 2330000,
        },

        {
            id: 12,
            name: "Giày Clog Unisex Crocs Classic - Eggplant",
            image: "../image/g12.webp",
            price: 1257900,
            decrease: 946320,
            discount: "-20%",
        },
        {
            id: 13,
            name: "Giày Clog Unisex Crocs Classic - Dark Brown",
            image: "../image/g13.webp",
            price: 2248000,
            promotion: "new",
        },
        {
            id: 14,
            name: "Giày Clog Unisex Crocs Classic - Olive",
            image: "../image/g14.webp",
            price: 1139000,
            promotion: "new",
        },
        {
            id: 15,
            name: "Giày Clog Unisex Crocs Classic - Metallic Gold",
            image: "../image/g15.webp",
            price: 2150000,
            decrease: 1920000,
            discount: "-20%",
        },
        {
            id: 16,
            name: "Giày Clog Unisex Crocs Classic - Multicolor Confetti",
            image: "../image/g16.webp",
            price: 1020000,
            promotion: "new",
        },
    ],
    Giaynu: [{
            id: 1,
            name: "Giày Crocs Brooklyn Luxe Cross Strap - Tan",
            image: "../image/ip17.jpg",
            price: 2130000,
            promotion: "new",
        },
        {
            id: 2,
            name: "Giày Crocs Brooklyn Luxe Cross Strap",
            image: "../image/ip18.jpg",
            price: 6550000,
            promotion: "new",
        },
        {
            id: 3,
            name: "Giày Crocs Brooklyn Sandals",
            image: "../image/ip19.jpg",
            price: 7200000,
            promotion: "new",
        },
        {
            id: 4,
            name: "Giày Crocs Brooklyn Luxe Clogs",
            image: "../image/ip20.jpg",
            price: 11650000,
            decrease: 9485000,
            discount: "-10%",
        },
        {
            id: 5,
            name: "Giày Crocs Brooklyn Luxe Clogs",
            image: "../image/ip20.jpg",
            price: 1165000,
            decrease: 1048500,
            discount: "-10%",
        },
        {
            id: 6,
            name: "Giày Crocs Brooklyn Sandals",
            image: "../image/ss6.jpg",
            price: 1500000,
            decrease: 1000000,
            discount: "-20%",
        },
        {
            id: 7,
            name: "Giày Crocs Brooklyn Luxe Clogs",
            image: "../image/ss7.jpg",
            price: 990000,
        },
        {
            id: 8,
            name: "Giày Crocs Brooklyn Sandals ",
            image: "../image/ss8.png",
            price: 550000,
        },
        {
            id: 9,
            name: "Giày Crocs Brooklyn Sandals",
            image: "../image/ss9.png",
            price: 1900000,
            promotion: "new",
        },
        {
            id: 10,
            name: "Giày Đế Xuồng Nữ Crocs Brooklyn Luxe Cross Strap",
            image: "../image/ss10.png",
            price: 3690000,
            promotion: "new",
        },
        {
            id: 11,
            name: "Giày Đế Xuồng Nữ Crocs Brookly",
            image: "../image/ss11.png",
            price: 6590000,
            promotion: "new",
        },
        {
            id: 12,
            name: "Crocs Stomp Fisherman Sandals",
            image: "../image/ss14.jpg",
            price: 2790000,
            decrease: 1910000,
            discount: "-17%",
        },
        {
            id: 13,
            name: "Crocs Pacer Literide 360",
            image: "../image/ss15.jpg",
            price: 2800000,
            promotion: "new",
        },
        {
            id: 14,
            name: "Crocs Baya Platform Sandals",
            image: "../image/ss16.jpg",
            price: 949000,
            promotion: "new",
        },
        {
            id: 15,
            name: "Crocs Mega Crush Clog",
            image: "../image/ss11.png",
            price: 959000,
            promotion: "new",
        },
        {
            id: 16,
            name: "Crocs Brooklyn Upper Low Wedge",
            image: "../image/ss7.jpg",
            price: 490000,
            promotion: "new",
        },
    ],
    Depnam: [{
            id: 1,
            name: "Dép Classic Clog",
            image: "../image/o1.jpg",
            price: 3900000,
            promotion: "new",
        },
        {
            id: 2,
            name: "Dép Crocband Clog",
            image: "../image/o2.jpg",
            price: 2900000,
            promotion: "new",
        },
        {
            id: 3,
            name: "Dép Baya Clog",
            image: "../image/o3.jpg",
            price: 3490000,
            decrease: 2192000,
            discount: "-20%",
        },
        {
            id: 4,
            name: "Dép Santa Cruz Clog",
            image: "../image/o14.jpg",
            price: 4990000,
            promotion: "new",
        },
        {
            id: 5,
            name: "Dép literide Clog",
            image: "../image/o5.png",
            price: 3990000,
            decrease: 3100000,
            discount: "-7%",
        },
        {
            id: 6,
            name: "Dép Classic Crocs Sandal",
            image: "../image/o6.jpg",
            price: 4490000,
        },
        {
            id: 7,
            name: "Dép Swiftwater Sandal",
            image: "../image/o7.jpg",
            price: 3990000,
        },
        {
            id: 8,
            name: "Dép Classic Flip",
            image: "../image/o8.jpg",
            price: 360000,
            decrease: 290000,
            discount: "-18%",
        },
        {
            id: 9,
            name: "ODép Bayaband Flip",
            image: "../image/o9.jpg",
            price: 4580000,
            promotion: "new",
        },
        {
            id: 10,
            name: "Dép Classic All-Terrain Clog",
            image: "../image/o10.jpg",
            price: 220000,
            promotion: "new",
        },
        {
            id: 11,
            name: "Dép Literide Pacer",
            image: "../image/o11.jpg",
            price: 4600000,
            promotion: "new",
        },
        {
            id: 12,
            name: "Dép Crocs CitiLane Clog",
            image: "../image/o7.png",
            price: 3490000,
            decrease: 3350000,
            discount: "-4%",
        },
        {
            id: 13,
            name: "Dép Classic Lined Clog",
            image: "../image/o13.jpg",
            price: 1600000,
            promotion: "new",
        },
        {
            id: 14,
            name: "Dép Work Clog",
            image: "../image/o14.jpg",
            price: 299000,
            promotion: "new",
        },
        {
            id: 15,
            name: "Dép Swiftwater Sandal",
            image: "../image/o8.jpg",
            price: 666000,
            decrease: 579000,
            discount: "-13%",
        },
        {
            id: 16,
            name: "Dép Classic Crocs Sandal",
            image: "../image/o11.jpg",
            price: 888000,
            promotion: "new",
        },
    ],

    Depnu: [{
            id: 1,
            name: "Dép quai ngang Unisex Crocs Classic Slide Black",
            image: "../image/r1.jpg",
            price: 1600000,
            promotion: "new",
        },
        {
            id: 2,
            name: "Dép quai ngang Unisex Crocs Crocband Slide Navy/White",
            image: "../image/r2.jpg",
            price: 2990000,
            promotion: "new",
        },
        {
            id: 3,
            name: "Dép quai ngang Unisex Crocs LiteRide Slide Charcoal/Slate Grey",
            image: "../image/r4.jpg",
            price: 950000,
            decrease: 760000,
            discount: "-20%",
        },
        {
            id: 4,
            name: "Dép quai ngang Unisex Crocs Baya Slide White ",
            image: "../image/r3.jpg",
            price: 1200000,
            promotion: "new",
        },
        {
            id: 5,
            name: "Dép quai ngang Unisex Crocs Classic II Slide Bone",
            image: "../image/r5.jpg",
            price: 3990000,
            decrease: 3210000,
            discount: "-20%",
        },
        {
            id: 6,
            name: "Dép quai ngang Unisex Crocs Classic Slide Tropical Teal ",
            image: "../image/r6.jpg",
            price: 2131000,
        },
        {
            id: 7,
            name: "Dép quai ngang Unisex Crocs All-Terrain Slide Sage Green",
            image: "../image/r7.jpg",
            price: 2290000,
        },
        {
            id: 8,
            name: "Dép quai ngang Unisex Crocs Swiftwater Wave Sandal Black ",
            image: "../image/r8.jpg",
            price: 1250000,
            decrease: 1000000,
            discount: "-20%",
        },
        {
            id: 9,
            name: "Dép quai ngang Unisex Crocs Classic Slide Citrus",
            image: "../image/r9.jpg",
            price: 1350000,
            promotion: "new",
        },
        {
            id: 10,
            name: "Dép quai ngang Unisex Crocs Classic II Slide Pink Lemonade",
            image: "../image/r10.jpg",
            price: 2500000,
            promotion: "new",
        },
        {
            id: 11,
            name: "Dép quai ngang Unisex Crocs Classic Slide Cerulean Blue",
            image: "../image/r1.jpg",
            price: 1600000,
            promotion: "new",
        },
        {
            id: 12,
            name: "Dép quai ngang Unisex Crocs LiteRide Slide Blush Pink ",
            image: "../image/r8.jpg",
            price: 5790000,
            decrease: 4632000,
            discount: "-20%",
        },
        {
            id: 13,
            name: "RDép quai ngang Unisex Crocs Classic II Slide Red",
            image: "../image/r7.jpg",
            price: 2480000,
            promotion: "new",
        },
        {
            id: 14,
            name: "Dép quai ngang Unisex Crocs Baya Slide Camo",
            image: "../image/r9.jpg",
            price: 1390000,
            promotion: "new",
        },
        {
            id: 15,
            name: "Dép quai ngang Unisex Crocs All-Terrain Slide Black/Charcoal",
            image: "../image/r2.jpg",
            price: 1050000,
            decrease: 810000,
            discount: "-20%",
        },
        {
            id: 16,
            name: "Dép quai ngang Unisex Crocs Classic Slide Sunshine Yellow",
            image: "../image/r10.jpg",
            price: 8420000,
            promotion: "new",
        },
    ],
};

const productsData2 = {
    newProducts: [{
            id: 1,
            name: "Giày VANS OLD SKOOL CANVAS/SUEDE PHANTOM",
            image: "../image/vans.png",
            price: 3550000,
            promotion: "new",
        },
        {
            id: 2,
            name: "Vans Old Skool Stackform",
            image: "../image/vans1.png",
            price: 1275000,
            promotion: "new",
        },
        {
            id: 3,
            name: "Vans UltraRange EXO ",
            image: "../image/vans2.png",
            price: 4550000,
            promotion: "new",
        },
        {
            id: 4,
            name: "Nike React",
            image: "../image/nike.png",
            price: 8000000,
            promotion: "new",
        },
    ],
    popularProduct: [{
            id: 1,
            name: "Giày Clog Unisex Crocs Salehe Bembury x The Pollex - Ube",
            image: "../image/best2.jpg",
            price: 2355000,
            promotion: "new",
        },
        {
            id: 2,
            name: "Giày Thời Trang Unisex Crocs Echo Sand Storm - Sesame",
            image: "../image/best1.png",
            price: 2600000,
        },
        {
            id: 3,
            name: "Giày Clog Unisex Crocs Echo Sand Storm",
            image: "../image/best3.jpg",
            price: 1600000,
            promotion: "new",
        },
        {
            id: 4,
            name: "Giày Thời Trang Unisex Crocs Echo Sand Storm - Moss",
            image: "../image/best4.png",
            price: 2350000,
        },
    ],
    discountProduct: [{
            id: 1,
            name: "Giày Clog Unisex Crocs All-Terrain Atlas Desert Brown",
            image: "../image/khuyenmai2.png",
            price: 199900,
            decrease: 159900,
            discount: "-10%",
        },
        {
            id: 2,
            name: "Giày Clog Unisex Crocs Classic Marbled Black/White",
            image: "../image/khuyenmai3.png",
            price: 2450000,
            decrease: 1911000,
            discount: "-22%",
        },
        {
            id: 3,
            name: "Giày Clog Unisex Crocs LiteRide 360 Navy/White",
            image: "../image/khuyenmai3.jpg",
            price: 700000,
            decrease: 420000,
            discount: "-40%",
        },
        {
            id: 4,
            name: "Giày Clog Unisex Crocs Crocband ",
            image: "../image/khuyenmai1.png",
            price: 1300000,
            decrease: 1150000,
            discount: "-15%",
        },
    ],
};